### ISSUE TITLE
Issues accessing to data

### ISSUE THREAD

**Issue by SusanaRR** [Leszek-Sieminski/RAhrefs#6]
First of all thanks for your help!

I'm trying to connect to ahrefs API using r. I have found your library and it did work to see the available reports and libraries. Now I would like to perform a basic query but I receive different errors:
ERROR 1 (the url and token has been omited)
RAhrefs::rah_backlinks (target = "domain.com/path/path",
                        token = Sys.getenv("token"),
                        mode = "exact", metrics = "url_from")

Error: nchar(token) not greater than 30

ERROR 2 (if i delete the token, then i get a different error, it seems is requesting the token)
RAhrefs::rah_backlinks (target = "domain.com/path/path",
                        mode = "exact", metrics = "url_from")

Error in do.call(rbind.data.frame, data_list$refpages) : 
  second argument must be a list

**Comment by Leszek-Sieminski** [comment]
Hi Susana!

It seems to me that there is a problem with API key as the root cause. Did you try to authenticate the token first or did you omit it? I mean this line:
`library("RAhrefs")

api_key <- "012345"

RAhrefs::rah_auth(api_key)`

There is a requirement I added to the functions that checks if the API key is a character string longer than 30 characters. I added it because the API key I had was long and it seemed to be reasonable at the time.

There are two possibilities:

1. you need to authenticate with the `rah_auth()` first - then you need to authenticate with it, try again and let me know if it solved the problem
2. you used `rah_auth()` function and API key is valid but shorter than 30 characters. This would mean that my requirement is based on a wrong assumptions. In this case, could you please check if the API key is valid in Ahrefs panel? And could you please let me know how many characters is your API key long?

Best,
Leszek

**Comment by SusanaRR** [comment]
Many thanks Leszek,

It seems that we need an API plan, even though we have some credits there. So nothing to do with your library.

Many thanks for your help!!
